# Note: Replace <YOUR_PASSWORD> with a password that meets SQL Server requirements:
# - At least 8 characters
# - Contains characters from 3 of these 4 sets:
#   - Uppercase letters (A-Z)
#   - Lowercase letters (a-z)
#   - Numbers (0-9)
#   - Symbols (!, #, $, etc.)
# - Avoid using @ in the password as it can cause URI parsing issues
dsn: mssql://sa:<YOUR_PASSWORD>@localhost:1433/blog_app
docPath: samples/mssql-with-tbls/docs
