# Sample configuration
# Note: Set MSSQL_PASSWORD environment variable to 'password' for this sample project
dsn: mssql://sa:${MSSQL_PASSWORD}@localhost:1433/blog_app
docPath: samples/mssql-with-tbls/docs
